# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Research Log
author:
  name: "Oh junho"
  email: "pinedance@gmail.com"
  homepage: "https://www.pinedance.click/"
  aboutme: "https://www.pinedance.click//aboutme/"
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

url: "https://research.pinedance.click" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
# baseurl: "/research" # the subpath of your site, e.g. /blog

twitter_username:
github_username:  pinedance

google_analytics: G-LLPXGJGZW2

# Build settings
# markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-datapage-generator
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor

custom:
  imagepath: //research.pinedance.click/data/images
  localfilepath: /resources
  thumbnailpath: /public/thumbnails

# Build settings
host: localhost
port: 8384

page_gen-dirs: false
page_gen:
- data: research
  template: page_gen/papers
  dir: papers
  # index_files: [true|false]
  # name: [field used to generate the filename]
  name_expr: record["year"] + "-" + record["noo"]
  title: title
  # title_expr: [a Ruby expression to generate the filename (alternative to title)]
  # extension: [extension used to generate the filename.]
  # filter: [property to filter data records by]
  filter_condition: "record['category'] == '논문'"
  # page_data_prefix: [prefix used to name variables]
  debug: false
- data: research
  template: page_gen/book
  dir: books
  # index_files: [true|false]
  # name: [field used to generate the filename]
  name_expr: record["year"] + "-" + record["noo"]
  title: title
  # title_expr: [a Ruby expression to generate the filename (alternative to title)]
  # extension: [extension used to generate the filename.]
  # filter: [property to filter data records by]
  filter_condition: "record['category'] == '저서역서'"
  # page_data_prefix: [prefix used to name variables]
  debug: false
- data: research
  template: page_gen/presentation
  dir: presentations
  # index_files: [true|false]
  # name: [field used to generate the filename]
  name_expr: record["year"] + "-" + record["noo"]
  title: title
  # title_expr: [a Ruby expression to generate the filename (alternative to title)]
  # extension: [extension used to generate the filename.]
  # filter: [property to filter data records by]
  filter_condition: "record['category'] == '발표'"
  # page_data_prefix: [prefix used to name variables]
  debug: false